<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\DirectoryService.Contracts\DirectoryService.Contracts.csproj" />
    <ProjectReference Include="..\DirectoryService.Domain\DirectoryService.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Departments\" />
    <Folder Include="PositionsMatrix\" />
    <Folder Include="Statistics\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="FluentValidation.DependencyInjectionExtensions" />
    <PackageReference Include="Microsoft.Extensions.Logging" />
  </ItemGroup>

</Project>
